###
GET http://localhost:3000/
###
POST http://localhost:3000/chat
  
{
  "text": "abri stardew valley",
  "apps": [
    { "id": "ultrakill", "name": "ULTRAKILL" },
    { "id": "stardew-valley", "name": "stardew valley" }
  ]
}